apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-services

bases:
 - ../base

resources:
  - ingress.yaml

namePrefix: iqt-action-dashboard-

commonLabels:
  project: iqt
  component: iqt-action-dashboard

images:
  - name: http-image
    newName: registry.digitalocean.com/hero7tech/iqt-pulse-dashboard
    