// Generated by https://quicktype.io

export interface IResponse {
  status: string;
  totalResults: number;
  articles: Article[];
}

export interface Article {
  source: Source;
  author: null | string;
  title: string;
  description: string;
  url: string;
  urlToImage: null | string;
  publishedAt: string;
  content: string;
}

export interface Source {
  id: ID | null;
  name: string;
}

export enum ID {
  ArsTechnica = 'ars-technica',
  BusinessInsider = 'business-insider',
  Engadget = 'engadget',
  TheVerge = 'the-verge',
  Wired = 'wired',
}

export interface IReminder {
  title: string;
  url: string;
  image: string;
  description: '';
}
