apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  type: service
  interface: http

configMapGenerator:
  - name: configmap-envs

secretGenerator:
  - name: secret-envs